Feature: import and export problems
UniversalOJ/UOJ-System pull request #114
Opened 2022-09-29 11:20 UTC by livingshade

Currently we only support transfer problem from UOJ to UOJ.
More manual tests required.

2022-09-29 11:26 UTC, billchenchina requested changes
删了好多文件 怎么回事呢

2022-09-29 11:36 UTC, livingshade commented
> 删了好多文件 怎么回事呢
应该是调.gitignore把 cache删了的原因，DDL要求先提交个PR，所以这里先挂着。而且目前的崩溃一致性和并发估计可能有问题，所以还需要测测改改。

2022-09-29 11:39 UTC, billchenchina commented
> 应该是调.gitignore把 cache删了的原因，DDL要求先提交个PR，所以这里先挂着。而且目前的崩溃一致性和并发估计可能有问题，所以还需要测测改改。

好👌

2022-10-31 15:02 UTC, closed without merging

2022-10-31 15:50 UTC, billchenchina commented
merged in #121.